apiVersion: v2
name: erp-system
description: Enterprise ERP System Helm Chart
version: 1.0.0
appVersion: 1.0.0

dependencies:
  - name: mongodb
    version: 14.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
  - name: redis
    version: 18.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: nats
    version: 1.x.x
    repository: https://nats-io.github.io/k8s-helm
    condition: nats.enabled
  - name: minio
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled
  - name: elasticsearch
    version: 8.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: elasticsearch.enabled
